### ISSUE TITLE
Asset Selector must close on "Cancel" button click

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/aem-assets-boilerplate#25]

**Comment by mfrisbey** [comment]
I'm not sure which "Cancel" button this is, but "rail mode" seems to provide a better user experience, in general. We may not need to handle this if we go that route: https://cq-dev.slack.com/archives/C05KMBFQNTD/p1692219557627929

**Comment by sdmcraft** [comment]
The `Cancel` button is this one
![image](https://github.com/hlxsites/aem-assets-boilerplate/assets/1191451/cce1a124-97e8-488d-9e09-f8424fe51206)

Raising a PR for fixing this (as its just uncommenting a couple of lines of code 😉  ). Once we have the "rail" view in, this would not be needed.
