### ISSUE TITLE
Improve sign-out experience 

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/aem-assets-boilerplate#28]
Right now, clicking on the "Sign Out" in asset selector does sign-out the use but does not provide any visual feedback that sign-out was successful. This needs to be improved.

**Comment by n-zimmermann** [comment]
Why do we need a sign out at all? I would suggest to remove it and rather focus on a "sticky" login experience. How long would a user stay logged in? How can we optimize the experience? Ideally, a user would do this only once.

**Comment by sdmcraft** [comment]
Yes, but I suppose we do need a sign-out for users explicitly wanted to end their logged in session. For e.g. if a user wants to switch to another IMS org or wants to log out after working on a shared device.

As for the login experience, the user stays logged in for 24 hours which I think it typical for all IMS sessions.

**Comment by mfrisbey** [comment]
I did some improvements as part of #27 where I moved the logout button to the header. Clicking on it seems to work well, too - in the prototype it will display a "Sign In" page again after signing out. Please feel free to take a look: https://github.com/mfrisbey/franklin-tutorial/tree/08782c367e3eec7615c847d572ae757be93c6cd5
