### ISSUE TITLE
Determine environment selection experience

### ISSUE THREAD

**Issue by mfrisbey** [hlxsites/aem-assets-boilerplate#39]
Currently, the AEM assets environment used by the asset picker is determined by a hard-coded configuration value. Will this be sufficient, or would we want to integrate the discovery service into the panel so that users can choose from their provisioned environments?

**Comment by sdmcraft** [comment]
> would we want to integrate the discovery service into the panel 

Wouldn't the asset selector MFE already do that? I tried removing the `repositoryId` configuration but ran into [this issue](https://cq-dev.slack.com/archives/C01RNQM16MP/p1692280318491949).

**Comment by mfrisbey** [comment]
> Wouldn't the asset selector MFE already do that?

That would be great! Let's see what the result is of your work removing the repositoryId

**Comment by sdmcraft** [comment]
I can confirm that the AS MFE provides a repository selection experience.

![image](https://github.com/hlxsites/aem-assets-boilerplate/assets/1191451/dbc433e9-d743-4b9b-9848-2c1685d6e974)

Please feel free to reopen if there's anything else we need to cover under this issue.
